services:
  gym-web-project:
    build: .
    env_file:
      - .env
    ports:
      - ${APPLICATION_PORT}:${CONTAINER_PORT}
    depends_on:
      - posgres
    environment:
      DB_HOST: db
      DB_NAME: ${DATABASE_SERVER_NAME}
      DB_USER: ${USER_NAME}
      DB_PASS: ${USER_PASSWORD}

  posgres:
    image: postgres:${POSGRESQL_VERSION}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_SERVER_NAME}
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${USER_PASSWORD}

volumes:
  pgdata:
