services:
  gym-web-project:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - posgres
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_USER: user
      DB_PASS: password

  posgres:
    image: postgres:16.8-alpine3.20
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  pgdata:
